# Generated by Django 6.0.7 on 2026-07-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
