# Generated by Django 6.1.2 on 2026-10-09 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_jobdeletionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_blob', to='recruitment.application')),
            ],
        ),
    ]
